import Head from 'next/head'
import Image from 'next/image'
import Link from "next/link"
import styles from '../styles/Home.module.css'
import {sanityClient,urlFor} from '../lib/sanity'

const recipesQuery=`*[_type=="recipe]{
  _id,
  name,
  slug,
  mainImage
}`;

export default function Home({data}) {
  const recipes=data.recipes
  return (
    <div className={styles.container}>
      <Head>
        <title>Intro to Next</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ul>
        {recipes?.length>0 && 
          recipes.map((recipe)=>{
            <li key={recipe._id} >
              <Link href="/" >
                <a>
                  <img src={urlFor(recipe.mainImage).url()} />
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          })}
      </ul>
      
    </div>
  )
}

export async function getStaticProps(){
  const recipes=await sanityClient.fetch(recipesQuery);
  return {props:{recipes}}
}